# Generated by Django 3.0 on 2022-04-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('exercise_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('duration', models.IntegerField(verbose_name='Duration in minutes')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Gym')),
                ('work_hours', models.ManyToManyField(to='gym.WorkingHours', verbose_name='Working hours')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Coach')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Training')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Client')),
                ('exercise_name', models.ManyToManyField(to='gym.Training', verbose_name='Exercises')),
            ],
        ),
    ]
