# Generated by Django 3.0 on 2022-04-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rank_training_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Gym'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Deposit number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, verbose_name='Currency')),
                ('subscription_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Subscription', verbose_name='Subscription number')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
        ),
    ]
