# Generated by Django 3.0 on 2022-04-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20220424_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('retailer_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Retailer name')),
                ('product_name', models.CharField(max_length=20, verbose_name='Product name')),
                ('product_type', models.CharField(max_length=20, verbose_name='Product type')),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.CreateModel(
            name='SportsWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[(None, 'Choose size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large'), ('XLL', '2X large')], max_length=3, verbose_name='Size')),
                ('type', models.CharField(max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Supplier')),
                ('sells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.SportsWear')),
                ('deposit_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Deposit')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Manager')),
                ('retailer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('deals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Gym')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Supplier')),
            ],
        ),
    ]
