# Generated by Django 3.0 on 2022-05-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20220424_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
